FROM thinkwhere/gdal-python:3.6-shippable

RUN pip install geoserver-rest

COPY publish_geotiff.py /app/publish_geotiff.py
COPY CONGONHAS_2018_2019_optimized.tif /app/CONGONHAS_2018_2019_optimized.tif

WORKDIR /app

CMD ["python", "publish_geotiff.py"]